services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://root:root@db:3306/validationapp
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: rzae0OT8qREGB58mRScZqZnMEzm7Kp43eKDq8BGVowc=
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: validationapp
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
