services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: validationapp
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
